spring:
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  redis:
    host: localhost
    port: 6379

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  access-secret: ${JWT_ACCESS_SECRET}
  refresh-secret: ${JWT_REFRESH_SECRET}
  time:
    access-exp: ${JWT_ACCESS_EXP}
    refresh-exp: ${JWT_REFRESH_EXP}

coolsms:
  access: ${COOLSMS_ACCESS}
  secret: ${COOLSMS_SECRET}
  phoneNumber: ${COOLSMS_PHONE_NUMBER}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${S3_REGION}
    stack:
      auto: false
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}

kakao:
  api:
    key: ${KAKAO_API_KEY}
    url: ${KAKAO_API_URL}
