spring:
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  redis:
    host: localhost
    port: 6379

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  access-secret: ${JWT_ACCESS_SECRET}
  refresh-secret: ${JWT_REFRESH_SECRET}
  time:
    access-exp: ${JWT_ACCESS_EXP}
    refresh-exp: ${JWT_REFRESH_EXP}

coolsms:
  access: ${COOLSMS_ACCESS}
  secret: ${COOLSMS_SECRET}
  phoneNumber: ${COOLSMS_PHONE_NUMBER}
  time:
    coolsms-exp: ${COOLSMS_EXP}
